### ISSUE TITLE
TabError when installing the library

### ISSUE THREAD

**Issue by arnaudmiribel** [ghpaetzold/LEXenstein#2]
Hi there,

I downloaded the latest release of LEXenstein and ran `python setup.py install` both on my native Python 3.6 and Anaconda environment Python 3.6. Here's the output :

```bash
>>> python setup.py install

running install
running build
running build_py
running install_lib
creating /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/spelling.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/morphadorner.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/util.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/identifiers.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/__init__.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/selectors.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/features.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/generators.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/rankers.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/evaluators.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/spelling.py to spelling.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/morphadorner.py to morphadorner.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/util.py to util.cpython-36.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (util.py, line 37)
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/identifiers.py to identifiers.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/__init__.py to __init__.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/selectors.py to selectors.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/features.py to features.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/generators.py to generators.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/rankers.py to rankers.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/evaluators.py to evaluators.cpython-36.pyc
running install_egg_info
Writing /anaconda3/envs/dlab/lib/python3.6/site-packages/LEXenstein-1.0-py3.6.egg-info
```

The installation completes -- but now if I try to load features : 

```python
>>> from lexenstein.features import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miribel/workspace/LEXenstein-2.0/lexenstein/features.py", line 1, in <module>
    from lexenstein.util import *
  File "/Users/miribel/workspace/LEXenstein-2.0/lexenstein/util.py", line 37
    res.append(cur_lines)
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

Don't exactly know how to fix that. 
Is it a python version problem ?

Thanks for your help.

**Comment by ghpaetzold** [comment]
Hi Arnaud,


I've just created a new latest version with some bug fixes:


https://github.com/ghpaetzold/LEXenstein/releases/latest


I removed the spaces/tabs problem.

However, LEXenstein is still a Python 2 tool, so you mind find some problems running it on a Python 3 environment. If you want, you can try and I will do my best to correct any bugs you find.


Regards,

_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: Arnaud <notifications@github.com>
Enviado: terça-feira, 27 de março de 2018 08:45:52
Para: ghpaetzold/LEXenstein
Cc: Subscribed
Assunto: [ghpaetzold/LEXenstein] TabError when installing the library (#2)


Hi there,

I downloaded the latest release of LEXenstein and ran python setup.py install both on my native Python 3.6 and Anaconda environment Python 3.6. Here's the output

>>> python setup.py install
running install
running build
running build_py
running install_lib
creating /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/spelling.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/morphadorner.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/util.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/identifiers.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/__init__.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/selectors.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/features.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/generators.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/rankers.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
copying build/lib/lexenstein/evaluators.py -> /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/spelling.py to spelling.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/morphadorner.py to morphadorner.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/util.py to util.cpython-36.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (util.py, line 37)
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/identifiers.py to identifiers.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/__init__.py to __init__.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/selectors.py to selectors.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/features.py to features.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/generators.py to generators.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/rankers.py to rankers.cpython-36.pyc
byte-compiling /anaconda3/envs/dlab/lib/python3.6/site-packages/lexenstein/evaluators.py to evaluators.cpython-36.pyc
running install_egg_info
Writing /anaconda3/envs/dlab/lib/python3.6/site-packages/LEXenstein-1.0-py3.6.egg-info


The installation completes -- but now if I try to load features :

>>> from lexenstein.features import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miribel/workspace/LEXenstein-2.0/lexenstein/features.py", line 1, in <module>
    from lexenstein.util import *
  File "/Users/miribel/workspace/LEXenstein-2.0/lexenstein/util.py", line 37
    res.append(cur_lines)
                        ^
TabError: inconsistent use of tabs and spaces in indentation


Don't exactly know how to fix that.
Is it a python version problem ?

Thanks for your help.

**Comment by arnaudmiribel** [comment]
The space/tab issue is indeed solved ! Thanks, that was very quick.

Was able to also install that required extra library `kenlm`, but there's indeed a version conflict when it comes to `urllib2`.

According to [urllib2's documentation](https://docs.python.org/2/library/urllib2.html) : 

> The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error. The [`2to3`](https://docs.python.org/2/library/2to3.html) tool will automatically adapt imports when converting your sources to Python 3.

I could thus use [`2to3`](https://docs.python.org/2/library/2to3.html) for myself. Not sure if you'd wanna do that for the source code though.

(Should I create another issue for porting this to Python 3 ?)

Best,

**Comment by ghpaetzold** [comment]
For the sake of agility, I suggest you use 2to3 for now...


For the next LEXenstein release I will port the entire code to Python 3. :)

And don't worry, I will just leave this issue open.


_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: Arnaud <notifications@github.com>
Enviado: terça-feira, 27 de março de 2018 09:24:47
Para: ghpaetzold/LEXenstein
Cc: Gustavo Henrique Paetzold; Comment
Assunto: Re: [ghpaetzold/LEXenstein] TabError when installing the library (#2)


The space/tab issue is indeed solved ! Thanks, that was very quick.

Was able to also install that required extra library kenlm, but there's indeed a version conflict when it comes to urllib2.

According to urllib2's documentation<https://docs.python.org/2/library/urllib2.html> :

The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error. The 2to3<https://docs.python.org/2/library/2to3.html> tool will automatically adapt imports when converting your sources to Python 3.

I could thus use 2to3<https://docs.python.org/2/library/2to3.html> for myself. Not sure if you'd wanna do that for the source code though.

(Should I create another issue for porting this to Python 3 ?)

Best,

**Comment by arnaudmiribel** [comment]
I tried `2to3` :

```bash
$ 2to3 --output-dir=LEXenstein-2.1_py3/ -W -n LEXenstein-2.1/
RefactoringTool: Files that were modified:
RefactoringTool: LEXenstein-2.1/setup.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/__init__.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/evaluators.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/features.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/generators.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/identifiers.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/morphadorner.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/rankers.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/selectors.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/spelling.py
RefactoringTool: LEXenstein-2.1/build/lib/lexenstein/util.py
RefactoringTool: LEXenstein-2.1/lexenstein/__init__.py
RefactoringTool: LEXenstein-2.1/lexenstein/evaluators.py
RefactoringTool: LEXenstein-2.1/lexenstein/features.py
RefactoringTool: LEXenstein-2.1/lexenstein/generators.py
RefactoringTool: LEXenstein-2.1/lexenstein/identifiers.py
RefactoringTool: LEXenstein-2.1/lexenstein/morphadorner.py
RefactoringTool: LEXenstein-2.1/lexenstein/rankers.py
RefactoringTool: LEXenstein-2.1/lexenstein/selectors.py
RefactoringTool: LEXenstein-2.1/lexenstein/spelling.py
RefactoringTool: LEXenstein-2.1/lexenstein/util.py
RefactoringTool: Warnings/messages while refactoring:
RefactoringTool: ### In file LEXenstein-2.1/build/lib/lexenstein/generators.py ###
RefactoringTool: Line 3: could not convert: import urllib2 as urllib
RefactoringTool: This module is now multiple modules
... (repeat last 2 lines 30 times)
```

So it all seems to work besides urllib2. I thus believe handling urllib2 would be the biggest concern when porting to Python 3.

Thanks,
